spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 123123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    propertise:
      hibernate:
#        show_sql: true
        format_sql: true

logging.level:
  org.habernate.SQL: debug
  org.hibernate.type: trace